// Codes renvoyés par les fonctions de la base → phrases courtes pour le terrain.
const M = {
  // version Cloudflare (comptes et entreprises)
  auth: 'Connectez-vous pour continuer.',
  no_company: "Ce compte n'est rattaché à aucune entreprise (ou en a été retiré).",
  unknown_function: "Cette fonction n'est pas encore disponible dans cette version.",
  not_available: "Cette fonction n'est pas encore disponible dans cette version.",
  invalid_role: 'Rôle inconnu.',
  unknown_user: "Personne inconnue dans votre entreprise.",
  unknown_hub: 'Lieu inconnu.',
  unknown_courier: 'Chauffeur inconnu.',
  owner_only: "Réservé au propriétaire de l'entreprise.",
  cannot_remove_self: 'Vous ne pouvez pas vous retirer vous-même.',
  cannot_remove_owner: "Le propriétaire de l'entreprise ne peut pas être retiré.",
  invalid_name: 'Indiquez un nom.',
  invalid_vehicle: 'Type de véhicule inconnu.',
  invalid_kind: 'Type de lieu inconnu.',
  invalid_position: 'Position GPS invalide.',
  invite_invalid: "Ce lien d'invitation n'est plus valable : demandez-en un nouveau.",
  email_taken: 'Un compte existe déjà avec cette adresse : connectez-vous.',
  weak_password: 'Mot de passe : 8 caractères au moins.',
  invalid_email: 'Adresse e-mail invalide.',
  invalid_company: "Indiquez le nom de l'entreprise.",
  rate: 'Trop de tentatives : réessayez dans quelques minutes.',
  server_error: 'Erreur du serveur. Réessayez dans un instant.',
  forbidden: 'Vous n\'avez pas le droit de faire cette action.',
  login_failed: 'Identifiants incorrects.',
  not_a_courier: 'Ce compte n\'est pas un compte chauffeur.',
  task_locked: 'Un autre préparateur s\'occupe de cette commande.',
  task_not_open: 'Cette préparation est déjà terminée.',
  task_not_picking: 'Prenez d\'abord la commande (« Je prends »).',
  not_your_task: 'Cette préparation est prise par quelqu\'un d\'autre.',
  unexpected_product: 'Ce produit n\'est pas dans la commande.',
  line_complete: 'Cet article est déjà complet.',
  invalid_quantity: 'Quantité invalide.',
  lines_pending: 'Des articles restent à scanner ou à déclarer en rupture.',
  nothing_to_pack: 'Aucun article prélevé : rien à emballer.',
  weight_required: 'Saisissez le poids du colis.',
  package_contents_mismatch: 'Le contenu des colis ne correspond pas aux articles prélevés.',
  items_required_for_multi_package: 'Répartissez les articles entre les colis.',
  invalid_package_count: 'Nombre de colis invalide.',
  unknown_package: 'Code colis inconnu.',
  bad_status: 'Ce colis n\'est pas à cette étape.',
  max_attempts_reached: 'Nombre de présentations atteint : retour au vendeur.',
  order_blocked: 'Commande annulée ou en litige : ne pas expédier.',
  order_cancelled: 'Commande annulée.',
  cod_not_confirmed: 'Paiement à la livraison pas encore confirmé par le client.',
  banned_number: 'Numéro de téléphone banni : commande refusée.',
  trip_not_loading: 'Ce voyage n\'est plus en chargement.',
  trip_not_open: 'Ce voyage n\'accepte plus de commande.',
  in_other_trip: 'Ce colis est déjà dans un autre voyage.',
  order_in_other_trip: 'Cette commande est déjà dans un autre voyage.',
  already_loaded: 'Colis déjà chargé.',
  package_not_staged: 'Ce colis n\'est pas à quai.',
  wrong_zone: 'Colis d\'une autre zone que ce voyage.',
  overweight: 'Poids maximal du véhicule dépassé.',
  too_many_packages: 'Nombre maximal de colis atteint.',
  needs_cooler: 'Colis « froid » : véhicule avec glacière obligatoire.',
  incompatible_live: 'Animaux vivants : véhicule dédié, pas de chargement mixte.',
  unloaded_packages: 'Des colis prévus ne sont pas chargés.',
  empty_trip: 'Voyage vide.',
  no_courier: 'Aucun chauffeur affecté.',
  vehicle_unavailable: 'Véhicule indisponible.',
  vehicle_busy: 'Véhicule déjà engagé dans un voyage.',
  vehicle_documents_expired: 'Documents du véhicule expirés : départ interdit.',
  courier_not_active: 'Chauffeur inactif.',
  license_expired: 'Permis du chauffeur expiré.',
  courier_has_open_trip: 'Ce chauffeur a un voyage non clôturé en caisse.',
  trip_not_sealed: 'Le départ n\'a pas encore été validé au quai.',
  signature_required: 'Signature du chauffeur obligatoire.',
  not_your_trip: 'Ce voyage n\'est pas le vôtre.',
  trip_not_in_progress: 'Le voyage n\'est pas en cours.',
  stop_closed: 'Cet arrêt est déjà terminé.',
  package_mismatch: 'Scannez tous les colis de cet arrêt, et seulement eux.',
  bad_code: 'Code client incorrect.',
  code_locked: 'Trop d\'essais : prenez une signature.',
  code_expired: 'Code expiré : prenez une signature.',
  proof_required: 'Code du client, ou signature et nom du réceptionnaire.',
  photo_required: 'Photo obligatoire.',
  amount_mismatch: 'Le montant encaissé doit être exactement le montant dû.',
  invalid_payment: 'Mode de paiement invalide.',
  call_required: 'Appelez d\'abord le client.',
  unknown_reason: 'Motif inconnu.',
  stops_pending: 'Des arrêts ne sont pas terminés.',
  same_person: 'Ce contrôle doit être fait par une autre personne.',
  trip_not_completed: 'Le voyage n\'est pas terminé.',
  already_remitted: 'Versement déjà enregistré.',
  credit_exceeds_invoice: 'Avoir supérieur à ce qui a été facturé.',
  not_found: 'Lien de suivi introuvable.',
  already_loaded_order: 'Le colis est déjà chargé : modification impossible.',
  outside_senegal: 'Position hors du Sénégal.',
  slot_unavailable: 'Créneau complet.',
  zone_not_served: 'Zone non desservie.',
  no_rate: 'Aucun tarif pour ce poids.',
  offline: 'Pas de réseau.',
  exceeds_cash: 'Montant supérieur aux espèces portées.',
  trip_not_on_road: 'Ce voyage n\'est pas sur la route.',
  invalid_destination: 'Voyage de destination invalide.',
  not_to_take: 'Ce colis n\'est pas à récupérer pour ce voyage.',
  transfer_pending: 'Récupérez d\'abord le colis auprès de l\'autre chauffeur.',
  not_a_delivery_stop: 'Cet arrêt est une collecte, pas une livraison.',
  not_a_pickup_stop: 'Cet arrêt est une livraison.',
  nothing_to_collect: 'Rien à collecter chez ce vendeur.',
  return_not_approved: 'Demande de retour non approuvée.',
  already_scheduled: 'Reprise déjà planifiée.',
  not_in_transit_to_hub: 'Ce colis n\'est pas en route vers le hub.',
  upload_failed: 'Envoi du fichier refusé.',
  invalid_path: 'Chemin de fichier invalide.',
  invalid_type: 'Format attendu : photo JPEG, PNG ou WebP.',
  empty_file: 'Fichier vide.',
  file_too_large: 'Fichier trop lourd (1,5 Mo au plus).',
  already_reconciled: 'Voyage déjà rapproché.',
  description_required: 'Décrivez l\'incident.',
  resolution_required: 'Indiquez la décision prise.',
  empty_credit_note: 'Choisissez au moins une ligne ou un montant.',
  invalid_period: 'Période invalide.',
  no_invoice: 'Pas encore de facture pour cette commande.',
  not_paid: 'Commande ni payée ni livrée : pas de facture.',
  unknown_incident: 'Incident inconnu.',
  unknown_invoice: 'Facture inconnue.',
  not_resellable: 'Seul un produit neuf ou en bon état se remet en vente.',
  invalid_recipient: 'Nom et téléphone de la personne requis.',
  order_closed: 'Commande déjà livrée ou annulée.',
  wave_size: 'Une vague regroupe de 2 à 12 commandes.',
  unknown_location: 'Emplacement inconnu.',
  unknown_product: 'Produit inconnu.',
  double_check_required: 'Double contrôle requis par une autre personne avant la mise à quai.',
  message_too_short: 'Message trop court.',
  message_too_long: 'Message trop long (1 000 caractères au plus).',
  // version Cloudflare, cycle C2 (commandes, tarifs, suivi)
  unknown_zone: 'Zone inconnue : choisissez une zone de livraison (Administration → Tarifs et zones).',
  unknown_company: 'Entreprise inconnue.',
  invalid_service: 'Service inconnu (standard, express ou programmé).',
  invalid_time: 'Heure invalide (HH:MM).',
  invalid_days: 'Choisissez au moins un jour de livraison.',
  invalid_polygon: 'Contour de zone invalide (3 points au moins).',
  zone_in_use: 'Des commandes en cours vont dans cette zone : marquez-la plutôt « non desservie ».',
  unknown_rate: 'Tarif inconnu.',
  invalid_customer: 'Nom du client et téléphone (9 chiffres au moins) obligatoires.',
  no_items: 'Ajoutez au moins un article.',
  too_many_items: 'Trop d\'articles dans une seule commande (50 au plus).',
  invalid_item: 'Chaque article doit avoir un nom.',
  duplicate_ref: 'Cette référence de commande existe déjà.',
  no_orders: 'Aucune commande à importer.',
  too_many_orders: 'Trop de lignes en un envoi (50 au plus).',
  not_cod: 'Cette commande est payée d\'avance : rien à confirmer.',
  unknown_order: 'Commande inconnue.',
  already_shipped: 'La commande est déjà partie : annulation impossible.',
  invalid_phone: 'Numéro de téléphone invalide.',
  already_confirmed: 'Commande déjà confirmée : appelez le service client pour l\'annuler.',
  outside_area: 'Position trop loin des zones livrées : vérifiez l\'épingle.',
  invalid_rating: 'Note de 1 à 5.',
  too_many_requests: 'Trop de demandes en peu de temps : réessayez dans une heure.',
  not_delivered: 'La commande n\'est pas encore livrée.',
  too_many_keys: 'Dix clés actives au plus : révoquez-en une.',
  unknown_key: 'Clé inconnue.',
  invalid_api_key: 'Clé d\'API absente ou invalide.',
  // version Cloudflare, cycles C3 et C4 (préparation, entrepôt, flotte, voyages)
  unknown_task: 'Préparation inconnue.',
  unknown_line: 'Ligne de préparation inconnue.',
  unknown_wave: 'Vague inconnue.',
  not_short: 'Cet article n\'est pas en rupture.',
  invalid_choice: 'Choix inconnu (remplacer, rembourser ou attendre).',
  invalid_date: 'Date invalide (AAAA-MM-JJ).',
  unknown_vehicle: 'Véhicule inconnu.',
  invalid_plate: 'Indiquez la plaque du véhicule.',
  invalid_capacity: 'Charge maximale du véhicule invalide.',
  invalid_ownership: 'Propriété du véhicule inconnue.',
  invalid_status: 'État invalide.',
  plate_taken: 'Un véhicule de l\'entreprise porte déjà cette plaque.',
  unknown_trip: 'Voyage inconnu.',
  unknown_stop: 'Arrêt inconnu.',
  trip_closed: 'Ce voyage est terminé.',
  trip_not_cancellable: 'Ce voyage est déjà parti : il ne peut plus être annulé.',
  not_in_trip: 'Ce colis n\'est pas dans ce voyage.',
  invalid_device: 'Appareil non reconnu.',
  suspended: 'Ce compte est suspendu.',
  origin: 'Requête refusée (origine inconnue).',
  // cycles 6 à 15
  expired_lot: 'Ce lot est déjà périmé : il ne se range pas, il repart chez le vendeur.',
  qty_exceeds: 'Quantité supérieure à ce qui reste dans ce lot.',
  unknown_lot: 'Lot inconnu.',
  reason_required: 'Indiquez un motif.',
  unknown_cause: 'Cause de retour inconnue ou désactivée.',
  not_a_return: 'Ce colis n\'est pas un retour.',
  dock_busy: 'Ce quai est occupé par un autre voyage.',
  no_free_dock: 'Aucun quai libre pour l\'instant.',
  unknown_dock: 'Quai inconnu.',
  code_required: 'Saisissez un code.',
  trip_started: 'Ce voyage est déjà parti.',
  over_cap: 'Indemnité supérieure au plafond (valeur assurée, ou plafond sans assurance).',
  already_closed: 'Cet incident est déjà clos.',
  nothing_to_answer: 'Cette proposition a déjà reçu une réponse.',
  value_too_high: 'Valeur trop élevée pour être assurée.',
  invalid_amount: 'Montant invalide.',
  device_blocked: 'Cet appareil a été bloqué par l\'administrateur. Contactez votre responsable.',
  device_revoked: 'Vous avez été déconnecté à distance. Reconnectez-vous.',
  cannot_block_self: 'Vous ne pouvez pas bloquer l\'appareil que vous utilisez.',
  no_session: 'Aucune session ouverte sur cet appareil.',
  unknown_device: 'Appareil inconnu.',
  invalid_hours: 'Durée invalide.',
  invalid_axis: 'Axe d\'analyse inconnu.',
  unknown_surcharge: 'Supplément inconnu.',
  invalid_code: 'Code invalide (lettres minuscules et _).',
  unknown_vendor: 'Vendeur inconnu.',
  nothing_to_drop: 'Aucun colis prêt à déposer.',
  not_at_vendor: 'Ce colis n\'est pas chez le vendeur (déjà reçu ou pas prêt).',
  in_pickup_trip: 'Ce colis est déjà prévu dans une collecte : retirez-le du voyage d\'abord.',
  unknown_booking: 'Réservation inconnue.',
  vendor_required: 'Choisissez un vendeur.',
  past_day: 'Ce jour est déjà passé.',
  call_closed: 'Cet appel de renfort est clos.',
  unknown_call: 'Appel de renfort inconnu.',
};

export function errText(e) {
  const raw = typeof e === 'string' ? e : e?.code ?? e?.error ?? e?.message ?? String(e);
  const code = String(raw).split(':')[0].trim();
  return M[code] ?? M[raw] ?? e?.text ?? raw;
}
